// preload.js | Version: 1.14
'use strict';
const { contextBridge, ipcRenderer } = require('electron');
const on = (ch) => (cb) => {
  const l = (_e, p) => cb(p);
  ipcRenderer.on(ch, l);
  return () => ipcRenderer.removeListener(ch, l);
};
const invoke = (ch) => (...a) => ipcRenderer.invoke(ch, ...a);
contextBridge.exposeInMainWorld('eveApi', {
  getVersion: invoke('app:getVersion'),
  getRefreshState: invoke('app:getRefreshState'),
  getSyncState: invoke('app:getSyncState'),
  getSequencerState: invoke('app:getSequencerState'),
  getEsiStatus: invoke('esi:status'),
  getEsiTimers: invoke('esi:timers'),
  getCharData: invoke('app:getCharData'),
  getWalletData: invoke('app:getWalletData'),
  getSkillsData: invoke('app:getSkillsData'),
  getClonesData: invoke('app:getClonesData'),
  getAssetsData: invoke('app:getAssetsData'),
  getAssetTree: invoke('assets-v2:getTree'),
  getStructureNames: invoke('app:getStructureNames'),
  getUniverseNames: invoke('app:getUniverseNames'),
  getLocationHierarchy: invoke('app:getLocationHierarchy'),
  downloadUpdate: invoke('updater:download'),
  dismissUpdate: invoke('updater:dismiss'),
  closeChangelog: invoke('updater:close-changelog'),
  listAccounts: invoke('accounts:list'),
  addAccount: invoke('accounts:add'),
  cancelLogin: invoke('accounts:cancelLogin'),
  removeAccount: invoke('accounts:remove'),
  refreshAll: invoke('accounts:refresh'),
  getCorpInfo: invoke('accounts:getCorpInfo'),
  getGroups: invoke('groups:get'),
  setGroup: invoke('groups:set'),
  setGroupPrimary: invoke('groups:setPrimary'),
  toggleGroup: invoke('groups:toggle'),
  getCharacterSkills: invoke('skills:getCharacter'),
  getAllSkills: invoke('skills:all'),
  clearCache: invoke('cache:clear'),
  readClipboardPlan: invoke('plans:readClipboard'),
  listPlans: invoke('plans:list'),
  savePlan: invoke('plans:save'),
  deletePlan: invoke('plans:delete'),
  exportPlanToClipboard: invoke('plans:exportClipboard'),
  getSettings: invoke('settings:get'),
  setSettings: invoke('settings:set'),
  showToast: invoke('toast:show'),
  testEnabled: invoke('test:enabled'),
  testRun: invoke('test:run'),
  getNotes: invoke('notes:get'),
  setNotes: invoke('notes:set'),
  forcePull: invoke('scheduler:forcePull'),
  debugGetLogs: invoke('debug:getLogs'),
  debugGetActions: invoke('debug:getActions'),
  debugRunAction: invoke('debug:runAction'),
  debugClearLogs: invoke('debug:clearLogs'),
  debugLog: invoke('debug:log'),
  onUpdateAvailable: on('updater:available'),
  onShowChangelog: on('updater:show-changelog'),
  onAccountsUpdated: on('accounts-updated'),
  onSkillCompleted: on('notification:skill-complete'),
  onWalletActivity: on('notification:wallet-activity'),
  onQueueWarning: on('notification:queue-warning'),
  onQueueEmpty: on('notification:queue-empty'),
  onRefreshState: on('refresh-state'),
  onDebugLog: on('debug:log')
});