// preload.js | Version: 1.17
'use strict';
const { contextBridge, ipcRenderer } = require('electron');
const on = (ch) => (cb) => {
  const l = (_e, p) => cb(p);
  ipcRenderer.on(ch, l);
  return () => ipcRenderer.removeListener(ch, l);
};
const invoke = (ch) => (...a) => ipcRenderer.invoke(ch, ...a);
contextBridge.exposeInMainWorld('eveApi', {
  getVersion: invoke('app:getVersion'),
  getRefreshState: invoke('app:getRefreshState'),
  getSyncState: invoke('app:getSyncState'),
  getSequencerState: invoke('app:getSequencerState'),
  getEsiStatus: invoke('esi:status'),
  getEsiTimers: invoke('esi:timers'),
  getCharData: invoke('app:getCharData'),
  getSkillsData: invoke('app:getSkillsData'),
  getCharacterSnapshot: invoke('app:getCharacterSnapshot'),
  getAssetTree: invoke('assets-v2:getTree'),
  getStructureNames: invoke('app:getStructureNames'),
  getUniverseNames: invoke('app:getUniverseNames'),
  getLocationHierarchy: invoke('app:getLocationHierarchy'),
  downloadUpdate: invoke('updater:download'),
  dismissUpdate: invoke('updater:dismiss'),
  closeChangelog: invoke('updater:close-changelog'),
  getChangelog: invoke('updater:get-changelog'),
  listAccounts: invoke('accounts:list'),
  addAccount: invoke('accounts:add'),
  cancelLogin: invoke('accounts:cancelLogin'),
  removeAccount: invoke('accounts:remove'),
  setIgnoreNoTraining: invoke('accounts:setIgnoreNoTraining'),
  refreshAll: invoke('accounts:refresh'),
  getCorpInfo: invoke('accounts:getCorpInfo'),
  getGroups: invoke('groups:get'),
  createGroup: invoke('groups:create'),
  setGroup: invoke('groups:set'),
  setGroupPrimary: invoke('groups:setPrimary'),
  toggleGroup: invoke('groups:toggle'),
  onGroupsUpdated: on('groups-updated'),
  onDataUpdated: on('data:updated'),
  getCharacterSkills: invoke('skills:getCharacter'),
  getAllSkills: invoke('skills:all'),
  clearCache: invoke('cache:clear'),
  readClipboardPlan: invoke('plans:readClipboard'),
  listPlans: invoke('plans:list'),
  savePlan: invoke('plans:save'),
  deletePlan: invoke('plans:delete'),
  exportPlanToClipboard: invoke('plans:exportClipboard'),
  getSettings: invoke('settings:get'),
  setSettings: invoke('settings:set'),
  pickSound: invoke('settings:pickSound'),
  showToast: invoke('toast:show'),
  startToastMove: invoke('toast:startMove'),
  endToastMove: invoke('toast:endMove'),
  testEnabled: invoke('test:enabled'),
  testRun: invoke('test:run'),
  getNotes: invoke('notes:get'),
  setNotes: invoke('notes:set'),
  getNotifications: invoke('notifications:getUnseen'),
  getAllNotifications: invoke('notifications:getAll'),
  markNotificationsSeen: invoke('notifications:markSeen'),
  getNotificationLastViewed: invoke('notifications:getLastViewed'),
  getAllUnseenCounts: invoke('notifications:getAllUnseenCounts'),
  getAllUnseenLevels: invoke('notifications:getAllUnseenLevels'),
  exportNotifications: invoke('notifications:export'),
  getPullerEligibility: invoke('scheduler:eligibility'),
  requeueEligible: invoke('scheduler:requeue'),
  forcePull: invoke('scheduler:forcePull'),
  debugGetLogs: invoke('debug:getLogs'),
  debugGetActions: invoke('debug:getActions'),
  debugRunAction: invoke('debug:runAction'),
  debugClearLogs: invoke('debug:clearLogs'),
  debugLog: invoke('debug:log'),
  onUpdateAvailable: on('updater:available'),
  onShowChangelog: on('updater:show-changelog'),
  onAccountsUpdated: on('accounts-updated'),
  onSkillCompleted: on('notification:skill-complete'),
  onWalletActivity: on('notification:wallet-activity'),
  onQueueWarning: on('notification:queue-warning'),
  onQueueEmpty: on('notification:queue-empty'),
  onQueueStalled: on('notification:queue-stalled'),
  onRefreshState: on('refresh-state'),
  onDebugLog: on('debug:log')
});