// preload.js
// VERSION: 1.7
'use strict';
const { contextBridge, ipcRenderer } = require('electron');
const on = (channel) => (callback) => {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};
contextBridge.exposeInMainWorld('eveApi', {
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  getRefreshState: () => ipcRenderer.invoke('app:getRefreshState'),
  getSyncState: () => ipcRenderer.invoke('app:getSyncState'),
  getSequencerState: () => ipcRenderer.invoke('app:getSequencerState'),
  getCharData: (id) => ipcRenderer.invoke('app:getCharData', id),
  getWalletData: (id) => ipcRenderer.invoke('app:getWalletData', id),
  getSkillsData: (id) => ipcRenderer.invoke('app:getSkillsData', id),
  getCorpAllianceData: () => ipcRenderer.invoke('app:getCorpAllianceData'),
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  addAccount: (s) => ipcRenderer.invoke('accounts:add', s),
  cancelLogin: () => ipcRenderer.invoke('accounts:cancelLogin'),
  removeAccount: (id) => ipcRenderer.invoke('accounts:remove', id),
  refreshAll: () => ipcRenderer.invoke('accounts:refresh'),
  getCorpInfo: (id) => ipcRenderer.invoke('accounts:getCorpInfo', id),
  getGroups: () => ipcRenderer.invoke('groups:get'),
  setGroup: (id, n) => ipcRenderer.invoke('groups:set', id, n),
  setGroupPrimary: (id) => ipcRenderer.invoke('groups:setPrimary', id),
  toggleGroup: (n) => ipcRenderer.invoke('groups:toggle', n),
  getSkillMeta: (ids) => ipcRenderer.invoke('skills:getMeta', ids),
  resolveNames: (ids) => ipcRenderer.invoke('skills:resolveNames', ids),
  getCharacterSkills: (id) => ipcRenderer.invoke('skills:getCharacter', id),
  getCharacterWallet: (id) => ipcRenderer.invoke('wallet:getCharacter', id),
  getCloneDetails: (id) => ipcRenderer.invoke('accounts:getCloneDetails', id),
  getCloneNickname: (id) => ipcRenderer.invoke('cloneNicknames:get', id),
  setCloneNickname: (id, n) => ipcRenderer.invoke('cloneNicknames:set', id, n),
  getAllCloneNicknames: () => ipcRenderer.invoke('cloneNicknames:getAll'),
  getPersonalAssets: (id) => ipcRenderer.invoke('assets:getPersonal', id),
  getCorpAssets: (id) => ipcRenderer.invoke('assets:getCorp', id),
  refreshAssetsNow: (id) => ipcRenderer.invoke('assets:refreshNow', id),
  getAssetsQueueState: () => ipcRenderer.invoke('assets:getQueueState'),
  getRawAssets: (id) => ipcRenderer.invoke('assets:getRaw', id),
  getCorpRawAssets: (id) => ipcRenderer.invoke('assets:getCorpRaw', id),
  queueAssetsRefresh: (id) => ipcRenderer.invoke('assets:queueRefresh', id),
  getAssetNames: (id) => ipcRenderer.invoke('assets:getNames', id),
  clearCache: (w) => ipcRenderer.invoke('cache:clear', w),
  readClipboardPlan: () => ipcRenderer.invoke('plans:readClipboard'),
  listPlans: () => ipcRenderer.invoke('plans:list'),
  savePlan: (p) => ipcRenderer.invoke('plans:save', p),
  deletePlan: (id) => ipcRenderer.invoke('plans:delete', id),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (p) => ipcRenderer.invoke('settings:set', p),
  importLegacy: () => ipcRenderer.invoke('import:legacy'),
  showToast: (t, b) => ipcRenderer.invoke('toast:show', t, b),
  testEnabled: () => ipcRenderer.invoke('test:enabled'),
  testRun: (c, p) => ipcRenderer.invoke('test:run', c, p),
  getNotes: (id) => ipcRenderer.invoke('notes:get', id),
  setNotes: (id, t) => ipcRenderer.invoke('notes:set', id, t),
  forcePull: (n) => ipcRenderer.invoke('scheduler:forcePull', n),
  debugGetLogs: () => ipcRenderer.invoke('debug:getLogs'),
  debugGetActions: () => ipcRenderer.invoke('debug:getActions'),
  debugRunAction: (n, p) => ipcRenderer.invoke('debug:runAction', n, p),
  debugClearLogs: () => ipcRenderer.invoke('debug:clearLogs'),
  debugLog: (p) => ipcRenderer.invoke('debug:log', p),
  onAccountsUpdated: on('accounts-updated'),
  onSkillCompleted: on('notification:skill-complete'),
  onWalletActivity: on('notification:wallet-activity'),
  onQueueWarning: on('notification:queue-warning'),
  onQueueEmpty: on('notification:queue-empty'),
  onRefreshState: on('refresh-state'),
  onDebugLog: on('debug:log')
});